export const SELECT_PROJECT_DIRECTORY = 'SELECT_PROJECT_DIRECTORY';
export const OPEN_PROJECT = 'OPEN_PROJECT';


export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const DECREMENT_ASYNC = 'DECREMENT_ASYNC';